---
# By setting the language to node_js, travis will execute the follwing steps:
# 1. Install the required node.js version (including npm)
# 2. Install dependencies with `npm install`
# 3. Execute tests with `npm travis`
language: node_js
node_js:
  - '0.10'
  
# We need a running neo4j-instance for our end2end-tests.
# The neo4j-server will listen on the standard port (7474)
services:
  - neo4j
  
# We use the grunt command-line tool for test execution, so we
# have to make sure, that the grunt executable is available
before_script:
  - npm install -g grunt-cli

# See http://about.travis-ci.org/docs/user/deployment/heroku/ for
# more information on automatic deployment to heroku
deploy:
  provider: heroku
  app: agilejs-ermahgerd
  api_key:
  - secure: ! 'EoE6kDFOwBochkz6SfEaZlzzn4mpKNaAR7C2ZYWcwXi60v7n7yv0IGruWKJJ
      PYrMdQTYrahsihKTq69nqMvdeSPvsLKxG88zlMohNNnqRGUdjeVDAEMClNfN
      aev8W5NsGp/j0Q2hmRagIFbVvi56moNhD14qBdAeWpUyitWr5GA='
